<a href="https://colab.research.google.com/github/dikshapandey00/data_analytics/blob/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random as ran
import pandas as pd

1. **Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.**


In [ ]:
np.array(range(6))

array([0, 1, 2, 3, 4, 5])

**2. Given a NumPy array 'arr', check if its data type is float64.** <br>
**arr = np.array([1.5, 2.6, 3.7])**

In [ ]:
arr = np.array([1.5, 2.6, 3.7])
if(arr.dtype) == 'float64':
  print(arr.dtype, " True")
else:
  print("False")

float64  True


**3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.**

In [ ]:
a = np.array([1 + 3j, 56 + 7j, 66 + 6j], dtype=complex)
print(a)
a.dtype

[ 1.+3.j 56.+7.j 66.+6.j]


dtype('complex128')

**4. Convert an existing NumPy array 'arr' of integers to float32 data type.**


In [ ]:
arr.astype('float32') #arr was declared in question 2

array([1.5, 2.6, 3.7], dtype=float32)

**5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.**

In [ ]:
arr = np.array([1.699999999999999999999999999, 233.45, 3.7], dtype = 'float64')
arr.astype('float32')
arr

array([  1.7 , 233.45,   3.7 ])

**6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.**


In [ ]:
def array_attributes(arr):
  a = {'shape =' : arr.shape , 'size = ' : arr.size, 'data type = ': arr.dtype}
  return a

array_attributes(arr)

{'shape =': (3,), 'size = ': 3, 'data type = ': dtype('float64')}

**7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.**





In [ ]:
def array_dimension(arr):
  return arr.ndim
array_dimension(arr)

1

**8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.**


In [ ]:
def item_size_info(arr):
  return arr.itemsize, arr.nbytes
item_size_info(a)

(16, 48)

**9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.**


In [ ]:
def array_strides(arr):
  return arr.strides

newarray = np.array([[1, 2, 3], [4, 5, 6]])
array_strides(newarray)

(24, 8)

**10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.**


In [ ]:
def shape_stride_relationship(arr):
  return arr.shape, arr.strides

shape_stride_relationship(newarray)

((2, 3), (24, 8))

**11. Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of
zeros with n elements.**


In [ ]:
def create_zeros_array():
  n = int(input('n: '))
  return np.zeros(n, dtype='int')

create_zeros_array()

n: 5


array([0, 0, 0, 0, 0])

**12. Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D <br>
NumPy array filled with ones of size rows x cols.**


In [ ]:
def create_ones_matrix():
  rows = int(input('rows: '))
  cols = int(input('cols: '))
  return np.ones((rows, cols))

create_ones_matrix()

rows: 2
cols: 6


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

**13. Write a function generate_range_array that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified
step.**


In [ ]:
def generate_range_array():
  start = int(input('start: '))
  stop = int(input('stop: '))
  step = int(input('step: '))
  return np.arange(start, stop, step)

generate_range_array()

start: 1
stop: 100
step: 5


array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

**14. Design a function generate_linear_space that takes two floats start, stop, and an integer num as
arguments and generates a NumPy array with num equally spaced values between start and stop
(inclusive).**


In [ ]:
def generate_linear_space():
  start = float(input('start: '))
  stop = float(input('stop: '))
  num = int(input('num: '))
  return np.linspace(start, stop, num)

generate_linear_space()

start: 1
stop: 100
num: 5


array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

**15. Create a function create_identity_matrix that takes an integer n as input and generates a square
identity matrix of size n x n using numpy.eye.**


In [ ]:
def create_identity_matrix():
  n = int(input('n: '))
  return np.eye(n)

create_identity_matrix()

n: 5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**16. Write a function that takes a Python list and converts it into a NumPy array.**



In [ ]:
def convertListToArray(list):
  return np.array(list)

convertListToArray([1, 2, 3])

array([1, 2, 3])

**17. Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the
same data.**


In [ ]:
def viewd(arr):
  view_arr = arr.view()
  return view_arr

print(arr)
viewd(arr)

[  1.7  233.45   3.7 ]


array([  1.7 , 233.45,   3.7 ])

**18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.**



In [ ]:
def concate(arr1, arr2, ax):
  return np.concatenate((arr1, arr2), axis=ax)

a1 = [[1,2,3],[1,2,3]]
a2 = [[4,5,6],[4,5,6]]
ax = int(input('axis : 1 or 0'))
concate(a1,a2,ax)

axis : 1 or 01


array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

**19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
 concatenate`**


In [ ]:
def concatenate(arr1, arr2):
  return np.concatenate((arr1, arr2), axis=1)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concatenate(arr1, arr2)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**20. Write a function that vertically stacks multiple NumPy arrays given as a list.**

In [ ]:
def vertical_stack(arr):
  return np.vstack(arr)

arr = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]])]
vertical_stack(arr)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size**

In [ ]:
def create_array(start, stop, step):
  return np.arange(start, stop + step, step)

start = int(input("Start: "))
stop = int(input("Stop: "))
step = int(input("Step: "))
create_array(start, stop, step)

Start: 0
Stop: 10
Step: 2


array([ 0,  2,  4,  6,  8, 10])

**22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).**

In [ ]:
def eq(start, stop):
  return np.linspace(start, stop, 10)

eq(0,1)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).**

In [ ]:
def logsp(start, stop):
  return np.logspace(np.log10(start), np.log10(stop), 5)

logsp(1,1000)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

**24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.**

In [ ]:
import pandas as pd
df = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)))
df

0   1   2
0  61  69   5
1  52  49  96
2  76  62  49
3  88  49   1
4  15  57  40

**25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.**

In [ ]:
def replace_negative(df, col):
  df[col] = np.where(df[col] < 0, 0, df[col])
  return df

df = pd.DataFrame(np.random.randint(-100, 100, size=(5, 3)))
print(df)
replace_negative(df, 0)
print("after function df: \n" ,df)

    0   1   2
0 -28  59   9
1  -8   8 -18
2  46 -26 -74
3  97 -69  13
4  36  64  72
after function df: 
     0   1   2
0   0  59   9
1   0   8 -18
2  46 -26 -74
3  97 -69  13
4  36  64  72


**26. Access the 3rd element from the given NumPy array.** <br>
 *arr = np.array([10, 20, 30, 40, 50])*

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

**27. Retrieve the element at index (1, 2) from the 2D NumPy array.**<br>
*arr_2d = np.array([[1, 2, 3],<br>
 [4, 5, 6],<br>
 [7, 8, 9]])*

In [ ]:
arr_2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
arr_2d[1,2]

6

 **28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.** <br>
 *arr = np.array([3, 8, 2, 10, 5, 7])*

In [ ]:
arr = np.array([3,8,2,10,5,7])
print(arr[arr > 5])

[ 8 10  7]


 **29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.**
* arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])*

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:6])

[3 4 5 6]


**30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.** <br>
 *arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])*

In [ ]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr_2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

**31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.**

In [ ]:
def extract_elements(arr, indices):
  return arr[indices]

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([0, 2])
extract_elements(arr, indices)

array([[1, 2, 3],
       [7, 8, 9]])

**32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.**

In [ ]:
def thresh(arr):
  return arr[arr > 5]

arr_1d = np.array([1,3,5,6,8,9])
thresh(arr_1d)

array([6, 8, 9])

**33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.**

In [ ]:
def extract_3d(arr, indices1, indices2, indices3):
  return arr[indices1, indices2, indices3]

arr_3d = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
indices1 = [0,1]
indices2 = [0,2]
indices3 = [0,1]

extract_3d(arr_3d, indices1, indices2, indices3)
#arr_3d.ndim

array([ 1, 17])

**34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.**

In [ ]:
def con(arr):
  return arr[(arr >5) & (arr < 10)]

ar = np.array([1,3,5,6,8,9,15,45,12])
con(ar)

array([6, 8, 9])

**35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.**

In [ ]:
def extract2(arr, indices1, indices2):
  return arr[indices1, indices2]

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

indices1 = [0]
indices2 = [2]

extract2(arr, indices1, indices2)

array([3])

**36.  Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.**

In [ ]:
arr = np.ones((3,3))
arr + 5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

**37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.**

In [ ]:
arr1 = np.ones((1,3))
arr2 = np.full((3,4),2)
arr1 = arr1.reshape(3,1)
print(arr1)
print(arr2)
arr2 * arr1

[[1.]
 [1.]
 [1.]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

**38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.**

In [ ]:
arr1 = np.array([[1,2,3,4]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr1 = arr1.reshape(4,1)
print(arr1)
print(arr2)
arr2 + arr1

[[1]
 [2]
 [3]
 [4]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

**39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.**

In [ ]:
arr1 = np.array([[1],[2],[3]])
arr2 = np.array([[4,5,6]])
arr1 = arr1.reshape(3,1)
arr1 + arr2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

**40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.**

In [ ]:
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[7, 8],[9, 10]])
arr2_reshaped = arr2.reshape(2, 2, 1)
arr1 * arr2_reshaped

array([[[ 7, 14, 21],
        [32, 40, 48]],

       [[ 9, 18, 27],
        [40, 50, 60]]])

**41. Calculate column-wise mean for the given array:** <br>
 *arr = np.array([[1, 2, 3], [4, 5, 6]])*

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

**42. Find maximum value in each row of the given array:**
 *arr = np.array([[1, 2, 3], [4, 5, 6]])*

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.max(axis=1)

array([3, 6])

**43. For the given array, find indices of maximum value in each column.**
 *arr = np.array([[1, 2, 3], [4, 5, 6]])*

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.argmax(axis=0)

array([1, 1, 1])

**44. For the given array, apply custom function to calculate moving sum along rows.**
 *arr = np.array([[1, 2, 3], [4, 5, 6]])*

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
def moving_sum(arr):
  return np.cumsum(arr, axis=1)

moving_sum(arr)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

**45. In the given array, check if all elements in each column are even.**
 *arr = np.array([[2, 4, 6], [3, 5, 7]])*


In [ ]:
arr = np.array([[2,4,6],[3,5,7]])
np.all(arr % 2 == 0, axis=0)

array([False, False, False])

**46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.**
 *original_array = np.array([1, 2, 3, 4, 5, 6])*

In [ ]:
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
original_array.reshape(m, n)

array([[1, 2, 3],
       [4, 5, 6]])

**47. Create a function that takes a matrix as input and returns the flattened array.**
 *input_matrix = np.array([[1, 2, 3], [4, 5, 6]])*

In [ ]:
def flatteninp(input_matrix):
  return input_matrix.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flatteninp(input_matrix)

array([1, 2, 3, 4, 5, 6])

**48. Write a function that concatenates two given arrays along a specified axis.**
 *array1 = np.array([[1, 2], [3, 4]])
 array2 = np.array([[5, 6], [7, 8]])*

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
np.concatenate((array1, array2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**49. Create a function that splits an array into multiple sub-arrays along a specified axis.**
 *original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])*

In [ ]:
def split_array(arr, axis, n):
  return np.split(arr, n, axis)
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_array(original_array, 0, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

**50. Write a function that inserts and then deletes elements from a given array at specified indices.**
 *original_array = np.array([1, 2, 3, 4, 5])
 indices_to_insert = [2, 4]
 values_to_insert = [10, 11]
 indices_to_delete = [1, 3]*

In [ ]:
def dele(arr, ind, vinsert, idelete):
  arr = np.insert(arr, ind, vinsert)
  print("after insertion: ", arr)
  arr = np.delete(arr, idelete)
  return arr
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
dele(original_array, indices_to_insert, values_to_insert, indices_to_delete)

after insertion:  [ 1  2 10  3  4 11  5]


array([ 1, 10,  4, 11,  5])

**51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.** <br>
**Perform element-wise addition between `arr1` and `arr2`.**

In [ ]:
arr1 = np.random.randint(10, size = 10)
arr2 = np.arange(1, 11)
arr1 + arr2

array([ 6,  2,  8,  9,  5, 12,  8, 10, 15, 17])

**52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.**

In [ ]:
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
arr1 - arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

**53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.**

In [ ]:
arr1 = np.random.randint(10,size = 5, dtype=int)
arr2 = np.arange(1, 6)
arr1 * arr2

array([ 7, 10,  6, 36, 25])

**54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.**


In [ ]:
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
arr1 / arr2

array([2., 2., 2., 2., 2.])

**55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.**


In [73]:
arr1 = np.arange(1,6)
arr2 = arr1[::-1]
np.exp([arr1**arr2])

array([[2.71828183e+00, 8.88611052e+06, 5.32048241e+11, 8.88611052e+06,
        1.48413159e+02]])

**56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.**

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [74]:
def count_substrings(arr, substring):
  count = 0
  for i in arr:
    if substring in i:
      count += 1
  return count
s = "hello"
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
count_substrings(arr, s)

3

**57. Write a function that extracts uppercase characters from a NumPy array of strings.**

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT']) <br>
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [75]:
def uppercase(arr):
  uchars = []
  for i in arr:
    for j in i:
      if j.isupper():
        uchars.append(j)
  return uchars
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

**58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.** <br>
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [76]:
def replace_substring(arr, old_substring, new_substring):
  for i in range(len(arr)):
    arr[i] = arr[i].replace(old_substring, new_substring)
  return arr
old_substring = "apple"
new_substring = "orange"
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
replace_substring(arr, old_substring, new_substring)

array(['orange', 'banana', 'grape', 'pineorang'], dtype='<U9')

**59. Write a function that concatenates strings in a NumPy array element-wise.** <br>
arr1 = np.array(['Hello', 'World'])<br>
arr2 = np.array(['Open', 'AI'])<br>


In [77]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
np.char.add(arr1, arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

**60. Write a function that finds the length of the longest string in a NumPy array.**<br>
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [78]:
def clen(arr):
  max = 0
  for i in arr:
    if max < len(i):
      max = len(i)
  return max
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
clen(arr)

9

**61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.**

In [80]:
data = np.random.randint(1, 1000, size=100)
print(np.mean(data), np.median(data), np.var(data), np.std(data))

480.9 488.5 80299.87 283.37231692598345


**62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.**

In [81]:
arr = np.random.randint(1, 100, size=50)
print(np.percentile(arr, 25), np.percentile(arr, 75))

20.25 69.0


**63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.**

In [84]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
corr = np.corrcoef(arr1, arr2)
# direction of a relationship between two variables
print(corr)

[[1. 1.]
 [1. 1.]]



**64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.**


In [85]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
np.dot(mat1, mat2)

array([[19, 22],
       [43, 50]])

**65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.**

In [86]:
arr = np.random.randint(10, 1000, size=50)
print(np.percentile(arr, [10, 50, 90]))

[110.  551.  902.5]



**66. Create a NumPy array of integers and find the index of a specific element.**


In [87]:
  arr = np.array([1, 2, 3, 4, 5])
  print(np.where(arr == 3))

(array([2]),)


**67. Generate a random NumPy array and sort it in ascending order.**

In [91]:
array = np.random.randint(0, 100, size=10)
np.sort(array)

array([ 8, 15, 33, 50, 50, 57, 67, 71, 86, 90])

**68. Filter elements >20 in the given NumPy array.**<br>
arr = np.array([12, 25, 6, 42, 8, 30])


In [93]:
arr = np.array([12, 25, 6, 42, 8, 30])
arr = arr[arr>20]
arr

array([25, 42, 30])

**69. Filter elements which are divisible by 3 from a given NumPy array.**
arr = np.array([1, 5, 8, 12, 15])

In [94]:
arr = np.array([1, 5, 8, 12, 15])
arr = arr[arr%3==0]
arr

array([12, 15])

**70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.**
arr = np.array([10, 20, 30, 40, 50])

In [95]:
arr = np.array([10, 20, 30, 40, 50])
arr = arr[(arr>=20) & (arr<=40)]
arr

array([20, 30, 40])

**71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.**
arr = np.array([1, 2, 3])

In [96]:
arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)

=


**72. For the given NumPy array, perform byte swapping in place using `byteswap()`.**
arr = np.array([1, 2, 3], dtype=np.int32)

In [97]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)

array([16777216, 33554432, 50331648], dtype=int32)

**73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.**<br>
arr = np.array([1, 2, 3], dtype=np.int32)

In [100]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr = arr.newbyteorder()
arr

array([16777216, 33554432, 50331648], dtype='>i4')


**74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.** <br>
arr = np.array([1, 2, 3], dtype=np.int32)

In [113]:
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == 'little':
  arr = arr.newbyteorder()
arr

array([1, 2, 3], dtype=int32)

**75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.** <br>
arr = np.array([1, 2, 3], dtype=np.int32)

In [112]:
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == 'little':
  print("byte swapping is necessary")
else:
  print("byte swapping is not necessary")

byte swapping is not necessary


**76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.**


In [111]:
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
if (arr1[0] == 100):
  print("yes affects")
else:
  print("no, does not affect")

no, does not affect


**77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.**


In [109]:
matrix = np.random.randint(1, 10, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 100
print("Original Matrix:")
print(matrix)
print("\nSlice View:")
print(view_slice)

Original Matrix:
[[100   9   7]
 [  5   8   1]
 [  9   8   5]]

Slice View:
[[100   9]
 [  5   8]]


**78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.**

In [108]:
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
view_b += 5
view_b

array([[ 6,  7],
       [ 9, 10]])

**79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`**.

In [106]:
orig_array = np.array(np.random.randint(1, 9, size=(2, 4)))
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 100
if (orig_array[0, 0] == 100):
  print("yes reflects change")
else:
  print("no")

yes reflects change



**80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.**


In [ ]:
data = np.random.randint(0, 10, size=(3, 4))
print("Original Array:")
print(data)
data_copy = np.copy(data[data > 5])

print("\nCopy of elements greater than 5:")
print(data_copy)

data_copy[0] = 100
print("\nModified copy:")
print(data_copy)

print("\nOriginal Array after modification in the copy:")
print(data)


Original Array:
[[9 8 2 8]
 [9 8 5 2]
 [4 3 8 9]]

Copy of elements greater than 5:
[9 8 8 9 8 8 9]

Modified copy:
[100   8   8   9   8   8   9]

Original Array after modification in the copy:
[[9 8 2 8]
 [9 8 5 2]
 [4 3 8 9]]


**81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.**

In [ ]:
A=np.array(np.random.randint(100, size=(5,5),dtype=int))
B=np.array(np.random.randint(100, size=(5,5), dtype=int))
print(A-B, "\n")
print(A+B)

[[ 27  32  24  58  17]
 [ -2 -12  22 -51   5]
 [ 13 -27  79 -24  11]
 [-30 -87  24 -12 -33]
 [-35  20  24  39 -71]] 

[[ 37  82 170 140 131]
 [ 80 112  92  93  23]
 [ 23  95  99 128 105]
 [ 82  95  32 150 105]
 [145  30 160 157  95]]


**82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.**


In [ ]:
C = np.matrix([[1,2],[2,3],[3,4]])
D = np.matrix([[1,2,3,4],[5,6,7,8]])
C@D

matrix([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [23, 30, 37, 44]])

**83. Create a matrix `E` and find its transpose.**

In [ ]:
E = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
E.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

**84. Generate a square matrix `F` and compute its determinant.**

In [ ]:
F = np.array(np.random.randint(100, size=(5,5)))
np.linalg.det(F)

2120628656.000001


**85. Create a square matrix `G` and find its inverse.**

In [ ]:
G = np.array([[1,2,3],[4,5,6],[7,8,10]])
if (np.linalg.det(G) != 0):
  print(np.linalg.inv(G))
else:
  print("Matrix is not invertible")

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
